---
title: "Test Analysis"
author: "Kaitlin Rommelfanger"
date: "2025-12-05"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r Explore something}
library(readr)
library(tidyverse)

#removed the two reps where intake radicle length was 10 in excel prior to import, this length is impossible 

sprout <- read_csv("Sprouting Experiment/data/E1 LARA_AVGE intake experiment Fall 2022 - MasterData.csv")
unique(sprout$IntakeDate)
#have a row that is all NAs, removing
sprout<-sprout%>%
  filter(!is.na(IntakeDate))

sprout<-sprout%>%filter(`IntakeDate`!="11/7/22")#remove the one random intake on 11/7 

##replace the <0.01 with 0.005 (essentially <RL is changed to half of the reporting limit)
sprout$`IntakeRadicleLength-cm`[sprout$`IntakeRadicleLength-cm`=="<0.1"]<-0.005

#change all NA to 0, in intake radical length
sprout$`IntakeRadicleLength-cm`[is.na(sprout$`IntakeRadicleLength-cm`)] <- 0


#split the tray number and treatment type into two separate columns so I can plot separately 
sprout<-sprout%>%separate(`Tray ID`, into = c("Treatment","Tray Number"), sep = " ")

#write an if else statement to make sprouted or not 0 or 1
#sprouted-1
#not sprouted-0
sprout$sprouted<-ifelse(sprout$SproutDate=="NA",'0','1')

#made not sprouted NA instead of 0, so changing NA to 0 in sprouted column
sprout$sprouted[is.na(sprout$sprouted)]<-0

#recoding STEER Basin to STEER so Figures match 
sprout$SiteID<-gsub("STEER Basin", "STEER", sprout$SiteID)


#filter the props by species
LARA<-sprout%>%filter(Species=="LARA")
AVGE<-sprout%>%filter(Species=="AVGE")


#going to remove an outlier in AVGE (likely typo)
AVGE<-AVGE%>%
  filter(PropaguleLength!=0.40)
#more outliers (likely typos too)
AVGE<-AVGE%>%
  filter(`Width-mm`!=1.3)
AVGE<-AVGE%>%
  filter(`Width-mm`!=1.5)
AVGE<-AVGE%>%
  filter(`Width-mm`!=1.7)

#remove outliers in LARA (likely errors)
LARA<-LARA%>%
  filter(`Width-mm`>=4)
LARA<-LARA%>%
  filter(`Width-mm`<=14)
LARA<-LARA%>%
  filter(Mass<=1.66)


#sprouted as numeric
AVGE$sprouted<-as.numeric(AVGE$sprouted)
LARA$sprouted<-as.numeric(LARA$sprouted)

#intake radicle length as numeric
AVGE$`IntakeRadicleLength-cm`<-as.numeric(AVGE$`IntakeRadicleLength-cm`)


#sproutdate and intake date as dates
sprout$SproutDate<-mdy(sprout$SproutDate)
sprout$IntakeDate<-mdy(sprout$IntakeDate)
sprout$RemovalDate<-mdy(sprout$RemovalDate)
```

Data Cleaning, Kaplein Meyer Curve and Log Rank Test


going to run a kaplin meyer curve analysis to analyze time until sprouting.. 
biostatssquid is a good source to walk through this analysis

The theory behind it all
https://biostatsquid.com/survival-time-analysis-easily-explained/
https://biostatsquid.com/kaplan-meier-curve/
https://biostatsquid.com/easy-log-rank-test/
https://biostatsquid.com/easy-cox-regression-for-survival-analysis/

the code (how to do it)
https://biostatsquid.com/easy-survival-analysis-r-tutorial/ 

another tutorial I like the first one better https://www.sthda.com/english/wiki/survival-analysis-basics
```{r}

library(survival)
library(ggsurvfit)
library(survminer)


#For this analysis we need 
#censoring status: the values in this column are 1 = event happened, 0 = censored (or TRUE and FALSE).

    #this is the sprouted column that we made above, where if it sprotued 1, if       not sprotued 0

#time to event: from the start time (e.g., time of diagnosis) to the end time (the event happened or the last day of follow-up

  #to do this I am calculating the days until the props either sprouted, or were      removed

#using an if else statement to do this, 
sprout<-sprout%>%
  mutate(DaysUntilEvent=  #making a new column
  ifelse(
  is.na(sprout$SproutDate), #if there is an NA in sproutdate
  RemovalDate -IntakeDate,  #then going to subtract removal date (calculates days until removal)
  SproutDate -IntakeDate )) #if there is anything but an NA, then subtract sprout date (calculates days until sprouting)

#looking at my new columns to make sure everything is Kosher
unique(sprout$DaysUntilEvent)
#found a -1, found NA's, weird gonna look at these
sproutcheck<-sprout%>%
  filter(is.na(DaysUntilEvent)|DaysUntilEvent=="-1")%>%
  select(Species, Treatment, IntakeDate, SproutDate, RemovalDate,DaysUntilEvent, notes)


#going to remove these NAs and -1, removal date isn't noted for these so they shouldnt be included in analysis
sprout<-sprout%>%
  filter(!is.na(DaysUntilEvent))%>%
  filter(DaysUntilEvent!="-1")

#double check they are removed
unique(sprout$DaysUntilEvent)

#now I'm checking to see if there are any remaining props without a sprout date and a removal date, there are not, but the prop being removed on day zero in the water treatment is weird, investigating more

sproutcheck<-sprout%>%
  filter(is.na(SproutDate)|is.na(RemovalDate))%>%
  select(Treatment,Species,SproutDate, RemovalDate, notes, DaysUntilEvent)%>%
  filter(DaysUntilEvent==0)

#looks like a prop was removed but date wasn't noted, so I am also going to remove this guy from the time series analysis, ok to keep for sprout or no sprout things, only one that has day until event 0 so will remove this row (i actually figured this out because i plotted the data and saw that one had been removed early, this is why its so important to visualize your data!!)

sprout<-sprout%>%
  filter(DaysUntilEvent!=0)

# data looks clean now, ok to leave a lot of these for binary analysis (sprout not sprout 0/1) but need to remove for time series analysis because don't know date of removal or sprouting

#check how many in each treatment
sproutcheck<-sprout%>%
  group_by(Species, Treatment)%>%
  summarise(n=n())

#Air-175 LARA 88 AVGE 87
#Fresh-177 LARA 89 AVGE 88
#Salt-179 LARA 89 AVGE 90
#Soil-180 LARA 90 AVGE 90


#check to make sure my columns are numeric
str(sprout)
sprout$sprouted<-as.numeric(sprout$sprouted)

#separate the two species into their own dataframes

LARA<-sprout%>%
  filter(Species=="LARA")

AVGE<-sprout%>%
  filter(Species=="AVGE")

#now we create the survival object using these two columns we created in sprout (censoring status=sprouted or not 0/1, and time to event=time until sprouted or was removed)

LARAsurv_obj <- Surv(time = LARA$DaysUntilEvent, event = LARA$sprouted)
AVGEsurv_obj<-Surv(time = AVGE$DaysUntilEvent, event = AVGE$sprouted)

#Log Rank Test (run this so we can plot it)
LARAsurv <- survfit(LARAsurv_obj ~ Treatment, data = LARA)
AVGEsurv<- survfit(AVGEsurv_obj ~ Treatment, data = AVGE)

#plotting LARA (fun=event plots it so it is time until event not number alive over time)
LARAplotobj<-ggsurvplot(LARAsurv, data=LARA,fun="event",
  palette = c("olivedrab","cornflowerblue","darkblue","salmon4"),conf.int = TRUE)

LARAplotobj

#the ggsurvplot() function doesn't just create a plot, it creates a list of things containing the plot, in order to add ggplot layers you have to pull the plot out of the list, then you can add titles and stuff on like normal

LARAplot<-LARAplotobj$plot+ #pulling out the plot from the list
  ggtitle("LARA")+#adding ggplot things like normal
  theme(legend.position = "bottom", plot.title = element_text(hjust = 0.5))
LARAplot

#plotting AVGE
AVGEplotobj<-ggsurvplot(AVGEsurv, data=AVGE,fun="event",#makes it cumulative rather than countdown
  palette = c("olivedrab","cornflowerblue","darkblue","salmon4"),conf.int = TRUE)
AVGEplotobj



#same thing for AVGE
AVGEplot<-AVGEplotobj$plot+ #pulling out the plot from the list
  ggtitle("AVGE")+#adding ggplot things like normal
  theme(legend.position = "bottom", plot.title = element_text(hjust = 0.5))
AVGEplot

#now time to stat, log rank test to test for statistical differences between the curves

logRankAVGE<-survdiff(Surv(time = AVGE$DaysUntilEvent, event = AVGE$sprouted) ~ Treatment, data = AVGE)

logRankAVGE

#Call:
#survdiff(formula = Surv(time = AVGE$DaysUntilEvent, event = AVGE$sprouted) ~ 
#    Treatment, data = AVGE)

#                 N Observed Expected (O-E)^2/E (O-E)^2/V
#Treatment=Air   87       14     98.9    72.884   136.362
#Treatment=Fresh 88       88     28.0   128.905   173.473
#Treatment=Salt  90       88     82.6     0.359     0.592
#Treatment=Soil  90       77     57.6     6.551     9.480

# Chisq= 257  on 3 degrees of freedom, p= <2e-16

#so we are looking at the number of samples in each treatment, the number that were observed to sprout, the number that would be expected if all treatments were the same, and the difference between observed and expected



LogRankLARA<-survdiff(Surv(time = LARA$DaysUntilEvent, event = LARA$sprouted) ~ Treatment, data = LARA)
print(LogRankLARA)

#survdiff(formula = Surv(time = LARA$DaysUntilEvent, event = LARA$sprouted) ~ 
#    Treatment, data = LARA)

#                 N Observed Expected (O-E)^2/E (O-E)^2/V
#Treatment=Air   88       26     90.9    46.355     89.43
#Treatment=Fresh 89       85     41.6    45.375     70.18
#Treatment=Salt  89       84     54.7    15.662     24.59
#Treatment=Soil  90       66     73.8     0.822      1.37

# Chisq= 144  on 3 degrees of freedom, p= <2e-16 

#now that we know there is a difference between treatments want to take into account the other variables use a Cox regression analysis to incorporate 

#so we are looking at the number of samples in each treatment, the number that were observed to sprout, the number that would be expected if all treatments were the same, and the difference between observed and expected
```

Cox Regression 
``` {r}
#looking at the structure of the dataframe and reclassifying things
str(LARA)
LARA$Float<-as.factor(LARA$Float)
LARA$Treatment<-as.factor(LARA$Treatment)
LARA<-as.data.frame(LARA)
LARA$SiteID<-as.factor(LARA$SiteID)

str(LARA)

#now that we know there is a difference between treatments want to take into account the other variables use a Cox regression analysis to incorporate 

#using a size characteristic, siteID, and Treatment
#not going to include float because they all basically flaoted

LARAcox<-coxph(Surv(time = LARA$DaysUntilEvent, event = LARA$sprouted)~Treatment+SiteID+Mass, data=LARA)

LARAcox
#Call:
#coxph(formula = Surv(time = LARA$DaysUntilEvent, event = LARA$sprouted) ~ 
#    Treatment + SiteID + Mass, data = LARA)

#                          coef exp(coef) se(coef)      z        p
#TreatmentFresh          2.3905   10.9194   0.2337 10.231  < 2e-16
#TreatmentSalt           1.8740    6.5145   0.2317  8.090 5.98e-16
#TreatmentSoil           1.2685    3.5554   0.2329  5.445 5.17e-08
#SiteIDSTEER             0.2101    1.2338   0.1568  1.339  0.18042
#SiteIDVessup Salt Pond  0.1666    1.1813   0.1610  1.035  0.30085
#Mass                    0.7547    2.1270   0.2678  2.818  0.00483

#Likelihood ratio test=154.3  on 6 df, p=< 2.2e-16
#n= 356, number of events= 261 

summary(LARAcox)
#this is the output of the cox regression

#now testing cox proportional hazards 
fit <- coxph(Surv(DaysUntilEvent, sprouted) ~ Treatment + SiteID + Mass,
             data = LARA)

ph_test <- cox.zph(fit)
print(ph_test)


AVGEcox<-coxph(Surv(time = AVGE$DaysUntilEvent, event = AVGE$sprouted)~Treatment+SiteID+Mass+Float, data=AVGE)

AVGEcox
```

